version: "3"
services:
        rabbitmq:
                image: rabbitmq:management
                ports:
                        - "5672:5672"
                        - "15672:15672"
                environment:
                        - RABBITMQ_DEFAULT_USER=user
                        - RABBITMQ_DEFAULT_PASS=password
        gamification:
                build:
                        context: gamification
                image: gamification:latest
                depends_on: 
                        - rabbitmq
