version: "3"
services:
  service-registry:
    build:
      context: service-registry
    image: service-registry:latest
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    networks:
      - backend
  gateway:
    build:
      context: gateway
    image: gateway:latest
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    depends_on:
      - rabbitmq
      - service-registry
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - backend
  gamification:
    build:
      context: gamification
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    networks:
      - backend
  multiplication:
    build:
      context: multiplication
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    networks:
      - backend
  ui:
    build:
      context: ui
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
