version: "3"
services:
        service-registry:
                        build:
                                context: service-registry
                        image: service-registry:latest
                        ports:
                          - "8761:8761"
                        networks:
                                - backend
        gateway:
                        build:
                                context: gateway
                        image: gateway:latest
                        depends_on:
                                # - rabbitmq
                                - service-registry
                        ports:
                          - "8000:8000"
                        networks:
                                - backend
networks:
  backend:
    driver: bridge
